### ISSUE TITLE
More advanced benchmarks

### ISSUE THREAD

**Issue by i-norden** [cerc-io/ipld-eth-statedb#14]
Benchmark at the eth_call level, by initializing an EVM with are various ipld-eth-statedb implementations or the geth levelDB implementation 

* EVM using ipld-eth-statedb that accesses ipld-eth-db state directy
* EVM using ipld-eth-statedb that accesses ipld-eth-db state by trie traversal
* EVM using geth StateDB

Also increasing db size, if feasible.

**Comment by telackey** [comment]
https://git.vdb.to/cerc-io/ipld-eth-statedb/issues/3
