### ISSUE TITLE
Decide where this should live

### ISSUE THREAD

**Issue by i-norden** [cerc-io/ipld-eth-statedb#4]
This uses some internal/unexported packages from geth, but it also modifies them so we'd have to copy the code for the most part even if we made this an internal geth package.

We have sort of 3 geth util library repos now:
- ipfs-ethdb
- go-eth-state-node-iterator
- ipld-eth-statedb

I think we have 3 options:
- Leave them as separate repos
- Internalized them all into geth
- Combine them into a single "geth util/auxiliary libraries" repo

An advantage of having them separate is visibility/accessibility, if we want them to stand alone as general packages that other people/projects can use it is nice to not have them buried a few directories deep in a fork of a large code base. But ipfs-ethdb has lost some of its generality in the recent v5 change (reverting to v0 ipfs blockstore format) and ipld-eth-statedb is very specific to our system.  go-eth-state-node-iterator is still generally useful.

A disadvantage is that it adds repos that need to be maintained and updated during the already unwieldy geth rebases.

The combined repo might be a good compromise, I recall you mentioned something like this in the past @ABastionOfSanity. Curious what your thoughts are generally since you are the one doing the geth rebases currently.

**Comment by AFDudley** [comment]
FWIW, I like the combined external repo.

**Comment by i-norden** [comment]
How does `ipld-eth-db-utils` sound? Doesn't exactly roll off the tongue but follows our literal naming conventions.

**Comment by i-norden** [comment]
Or just `ipld-eth-utils`, which might be more appropriate as the iterator doesn't need to be used with/for ipld-eth-db.

**Comment by i-norden** [comment]
It will live in https://github.com/cerc-io/ipld-eth-utils/issues/1
