### ISSUE TITLE
Basic benchmarks

### ISSUE THREAD

**Issue by i-norden** [cerc-io/ipld-eth-statedb#9]
Comparing 
* ipld-eth-statedb
* geth [statedb](https://github.com/cerc-io/go-ethereum/blob/v1.11.2-statediff-v4/core/state/statedb.go) using [levelDB ethdb](https://github.com/cerc-io/go-ethereum/blob/v1.11.2-statediff-v4/ethdb/leveldb/leveldb.go)
* geth statedb using [ipfs-ethdb](https://github.com/cerc-io/ipfs-ethdb)

One complication is that to use ipfs-ethdb on v5 we need to write another modified StateDB that passes in CIDs instead of hashes, see https://github.com/cerc-io/ipfs-ethdb/pull/50

Instead we could compare against v4 ipfs-ethdb. The changes made to the blockstore going from v4 to v5 (switching from mh_key to cid as the key, see https://github.com/cerc-io/ipld-eth-db/issues/122) should not have an appreciable impact on the benchmarks.

**Comment by roysc** [comment]
In progress at https://github.com/cerc-io/eth-statedb-benchmark/

**Comment by roysc** [comment]
Preliminary results with 1000 owned accounts, 1000 contracts (1 slot each), and 5000 blocks (1 tx per block):
```
BenchmarkStateDB/Geth_StateDB
BenchmarkStateDB/Geth_StateDB-10         	19091065	        73.71 ns/op
BenchmarkStateDB/IPLD_StateDB
BenchmarkStateDB/IPLD_StateDB-10         	22462786	        56.88 ns/op
BenchmarkStateDB/IPFS_EthDB
BenchmarkStateDB/IPFS_EthDB-10           	      90	  14071169 ns/op
```
The path-indexed StateDB solidly faster than LevelDB, and CID-indexed full-trie StateDB dramatically slower. Roughly in line with expectations TMU.

**Comment by i-norden** [comment]
That's really promising!! Especially with what @dboreham had mentioned in mind: the performance discrepancy should continue to widen as we work with larger data sets.

**Comment by i-norden** [comment]
@roysc the next benchmarks we should do is to test eth_call performance, which will require initializing a EVM with these various StateDBs.
